docker_builder:
    name: CI
    env:
        HOME: /root
        DEBIAN_FRONTEND: noninteractive
    build_script: |
        apt-get -q update
        apt-get -q install -y bats cryptsetup gcc golang make podman libbtrfs-dev libgpgme-dev libdevmapper-dev
        gcc -v
        go version
        make
